import React, { useState } from 'react';
import { useLanguage } from '../context/LanguageContext';

export interface DemoDataBadgeProps {
  type?: 'simulated' | 'ai_estimate' | 'prototype' | 'reference' | 'live' | 'ai_assisted_estimate';
  className?: string;
  tooltipText?: string;
  showInlineToggle?: boolean;
}

export const DemoDataBadge: React.FC<DemoDataBadgeProps> = ({
  type = 'prototype',
  className = '',
  tooltipText,
  showInlineToggle = false,
}) => {
  const { t } = useLanguage();
  const [showTooltip, setShowTooltip] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);

  const isAiAssisted = type === 'ai_assisted_estimate';
  const isLive = type === 'live';

  const getLabel = () => {
    switch (type) {
      case 'live':
        return t.liveMandiTicker || 'Live Agmarknet Data';
      case 'ai_assisted_estimate':
        return t.aiAssistedEstimateBadge || 'AI-Assisted Estimate (LLM-based)';
      case 'ai_estimate':
        return t.aiEstimate || 'AI Estimate';
      case 'reference':
        return t.referencePriceData || 'Reference Data';
      case 'simulated':
        return t.simulatedData || 'Simulated Data';
      case 'prototype':
      default:
        return t.prototypeData || 'Prototype Data';
    }
  };

  const getDefaultTooltip = () => {
    switch (type) {
      case 'live':
        return 'Connected to live official Agmarknet mandi data feed via api.data.gov.in.';
      case 'ai_assisted_estimate':
        return (
          t.aiAssistedEstimateExplanation ||
          'This estimate is generated by an AI language model based on general market patterns, not a trained statistical model on historical price data. A backtested forecasting model (LightGBM trained on historical Agmarknet data with tracked accuracy) is planned for a future version.'
        );
      case 'ai_estimate':
        return 'Generated by FarmiGo AI based on seasonal trends and historical mandi patterns. For advisory and demonstration purposes.';
      case 'reference':
        return 'Aggregated reference mandi benchmark data. Connect live Agmarknet API credentials in settings for real-time district feeds.';
      case 'simulated':
        return 'Simulated demo data for prototype preview purposes.';
      case 'prototype':
      default:
        return 'Demonstration model. Real-time transactions require verified APMC/e-NAM account integration.';
    }
  };

  const getBadgeStyle = () => {
    if (isLive) {
      return 'bg-emerald-50 text-emerald-800 border-emerald-300 hover:bg-emerald-100';
    }
    if (isAiAssisted) {
      return 'bg-indigo-50/90 text-indigo-700 border-indigo-200/90 hover:bg-indigo-100/80';
    }
    return 'bg-amber-50 text-amber-800 border-amber-300/80 hover:bg-amber-100';
  };

  const getIcon = () => {
    if (isLive) return 'sensors';
    if (isAiAssisted) return 'psychology';
    return 'info';
  };

  const getIconColor = () => {
    if (isLive) return 'text-emerald-600 animate-pulse';
    if (isAiAssisted) return 'text-indigo-600';
    return 'text-amber-600';
  };

  const explanation = tooltipText || getDefaultTooltip();

  return (
    <div className={`relative inline-flex flex-col items-start ${className}`}>
      <div className="inline-flex items-center gap-1.5 flex-wrap">
        <span
          className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-mono font-semibold shadow-2xs cursor-help select-none transition-colors border ${getBadgeStyle()}`}
          onMouseEnter={() => setShowTooltip(true)}
          onMouseLeave={() => setShowTooltip(false)}
          onClick={() => {
            if (isAiAssisted || showInlineToggle) {
              setIsExpanded((prev) => !prev);
            } else {
              setShowTooltip((prev) => !prev);
            }
          }}
        >
          <span className={`material-symbols-outlined text-[12px] ${getIconColor()}`}>
            {getIcon()}
          </span>
          <span>{getLabel()}</span>
        </span>

        {isAiAssisted && (
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              setIsExpanded((prev) => !prev);
            }}
            onMouseEnter={() => setShowTooltip(true)}
            onMouseLeave={() => setShowTooltip(false)}
            aria-label="Model transparency info"
            className="inline-flex items-center justify-center w-5 h-5 rounded-full text-indigo-600 hover:bg-indigo-100/70 transition-colors cursor-pointer"
            title={explanation}
          >
            <span className="material-symbols-outlined text-[14px]">info</span>
          </button>
        )}
      </div>

      {showTooltip && !isExpanded && (
        <div
          className={`absolute bottom-full left-0 mb-1.5 z-50 p-2.5 bg-slate-900 text-white text-[11px] font-medium rounded-xl shadow-xl border border-slate-700 pointer-events-none animate-fade-in leading-relaxed text-left ${
            isAiAssisted ? 'w-72 sm:w-80' : 'w-56 text-center'
          }`}
        >
          {isAiAssisted && (
            <div className="text-[10px] font-bold text-indigo-300 uppercase tracking-wider mb-1 flex items-center gap-1">
              <span className="material-symbols-outlined text-xs">verified</span>
              {t.aiAssistedEstimateInfoTitle || 'Forecast Methodology'}
            </div>
          )}
          {explanation}
          <div className="absolute top-full left-4 -mt-1 border-4 border-transparent border-t-slate-900" />
        </div>
      )}

      {isAiAssisted && isExpanded && (
        <div className="mt-2 p-3 bg-indigo-50/90 border border-indigo-200/90 rounded-2xl text-[11px] text-slate-700 leading-relaxed max-w-md animate-fade-in shadow-2xs">
          <div className="flex items-center justify-between gap-2 font-bold text-indigo-900 text-[11px] mb-1">
            <span className="flex items-center gap-1">
              <span className="material-symbols-outlined text-xs text-indigo-600">info</span>
              {t.aiAssistedEstimateInfoTitle || 'Forecast Methodology & Transparency'}
            </span>
            <button
              type="button"
              onClick={() => setIsExpanded(false)}
              className="text-slate-400 hover:text-slate-600 text-xs p-0.5 rounded cursor-pointer"
            >
              <span className="material-symbols-outlined text-sm">close</span>
            </button>
          </div>
          <p className="text-slate-600 font-medium">
            {explanation}
          </p>
        </div>
      )}
    </div>
  );
};
